"use client";

import { FormEvent, useState } from "react";

type Weight = { id: string; measured_at: string; normalized_kg: number; source_value: number; source_unit: "kg" | "lb"; source: string; };
type Activity = { id: string; activity_type: string; started_at: string; ended_at: string; duration_seconds: number; source: string; };
type WeightValues = { measured_at: string; value: string; unit: "kg" | "lb"; source: string; };
type ActivityValues = { activity_type: string; started_at: string; ended_at: string; source: string; };

function errorMessage(body: unknown, fallback: string) { if (typeof body === "object" && body && "detail" in body) { const detail = (body as { detail: unknown }).detail; if (typeof detail === "string") return detail; if (Array.isArray(detail)) return detail.map((item) => typeof item === "object" && item && "msg" in item ? String(item.msg) : String(item)).join(" "); } return fallback; }
function localParts(value: Date) { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Amsterdam", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(value); const get = (type: string) => parts.find((part) => part.type === type)?.value; return `${get("year")}-${get("month")}-${get("day")}T${get("hour")}:${get("minute")}`; }
function currentLocalTime() { return localParts(new Date()); }
function amsterdamIso(value: string) { const [date, time] = value.split("T"); const [year, month, day] = date.split("-").map(Number); const [hour, minute] = time.split(":").map(Number); const raw = Date.UTC(year, month - 1, day, hour, minute); const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Amsterdam", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(raw)); const get = (type: string) => Number(parts.find((part) => part.type === type)?.value); const zoned = Date.UTC(get("year"), get("month") - 1, get("day"), get("hour"), get("minute")); return new Date(raw - (zoned - raw)).toISOString(); }
function durationSeconds(start: string, end: string) { return Math.round((new Date(amsterdamIso(end)).getTime() - new Date(amsterdamIso(start)).getTime()) / 1000); }
function blankWeight(): WeightValues { return { measured_at: currentLocalTime(), value: "", unit: "kg", source: "manual" }; }
function blankActivity(): ActivityValues { const now = currentLocalTime(); return { activity_type: "", started_at: now, ended_at: now, source: "manual" }; }

export function HealthPage({ initialWeights, initialActivities, loadError }: { initialWeights: Weight[]; initialActivities: Activity[]; loadError?: string | null }) {
  const [weights, setWeights] = useState(initialWeights); const [activities, setActivities] = useState(initialActivities);
  const [weightEdit, setWeightEdit] = useState<Weight | null>(null); const [activityEdit, setActivityEdit] = useState<Activity | null>(null);
  const [weight, setWeight] = useState<WeightValues>(blankWeight); const [activity, setActivity] = useState<ActivityValues>(blankActivity);
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  function editWeight(item?: Weight) { setWeightEdit(item ?? null); setWeight(item ? { measured_at: localParts(new Date(item.measured_at)), value: String(item.source_value), unit: item.source_unit, source: item.source } : blankWeight()); setError(""); }
  function editActivity(item?: Activity) { setActivityEdit(item ?? null); setActivity(item ? { activity_type: item.activity_type, started_at: localParts(new Date(item.started_at)), ended_at: localParts(new Date(item.ended_at)), source: item.source } : blankActivity()); setError(""); }
  async function saveWeight(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const response = await fetch(weightEdit ? `/api/health/weights/${weightEdit.id}` : "/api/health/weights", { method: weightEdit ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...weight, measured_at: amsterdamIso(weight.measured_at), value: Number(weight.value) }) }); if (!response.ok) { setError(errorMessage(await response.json().catch(() => null), "Gewicht kon niet worden bewaard.")); setSaving(false); return; } const saved: Weight = await response.json(); setWeights((current) => weightEdit ? current.map((item) => item.id === saved.id ? saved : item) : [saved, ...current]); editWeight(); setSaving(false); }
  async function saveActivity(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const response = await fetch(activityEdit ? `/api/health/activities/${activityEdit.id}` : "/api/health/activities", { method: activityEdit ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...activity, started_at: amsterdamIso(activity.started_at), ended_at: amsterdamIso(activity.ended_at), duration_seconds: durationSeconds(activity.started_at, activity.ended_at) }) }); if (!response.ok) { setError(errorMessage(await response.json().catch(() => null), "Activiteit kon niet worden bewaard.")); setSaving(false); return; } const saved: Activity = await response.json(); setActivities((current) => activityEdit ? current.map((item) => item.id === saved.id ? saved : item) : [saved, ...current]); editActivity(); setSaving(false); }

  return <main className="mx-auto min-h-screen max-w-5xl px-5 py-6 sm:px-8 sm:py-10"><a className="text-cyan-300 underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300" href="/">← Terug naar Vandaag</a><header className="mt-5"><h1 className="text-3xl font-semibold text-white sm:text-4xl">Gezondheid</h1><p className="mt-1 text-slate-400">Handmatige metingen en activiteiten. Geen medische interpretatie.</p></header>
    {loadError && <p className="mt-6 text-sm text-red-300" role="alert">{loadError}</p>}
    <section className="mt-8 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-start justify-between gap-3"><h2 className="text-xl font-semibold text-white">Gewicht</h2><button className="rounded bg-cyan-300 px-3 py-2 text-sm font-medium text-slate-950" type="button" onClick={() => editWeight()}>Gewicht toevoegen</button></div><div className="mt-4 grid gap-3" aria-label="Gewichtsmetingen">{weights.map((item) => <article className="rounded border border-slate-800 p-3" key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium text-white">{item.normalized_kg.toLocaleString("nl-NL")} kg</p><p className="text-sm text-slate-400">{new Intl.DateTimeFormat("nl-NL", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Amsterdam" }).format(new Date(item.measured_at))} · {item.source}</p></div><button className="rounded border border-slate-700 px-3 py-2 text-sm text-slate-100" type="button" onClick={() => editWeight(item)}>Bewerken</button></div></article>)}{!weights.length && <div className="rounded border border-dashed border-slate-700 p-4 text-slate-300"><p>Nog geen gewichtsmetingen.</p><button className="mt-3 rounded bg-cyan-300 px-3 py-2 text-sm font-medium text-slate-950" type="button" onClick={() => editWeight()}>Gewicht toevoegen</button></div>}</div></div>
      <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-start justify-between gap-3"><h2 className="text-xl font-semibold text-white">Activiteit</h2><button className="rounded bg-cyan-300 px-3 py-2 text-sm font-medium text-slate-950" type="button" onClick={() => editActivity()}>Activiteit toevoegen</button></div><div className="mt-4 grid gap-3" aria-label="Activiteiten">{activities.map((item) => <article className="rounded border border-slate-800 p-3" key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium text-white">{item.activity_type}</p><p className="text-sm text-slate-400">{Math.round(item.duration_seconds / 60)} min · {new Intl.DateTimeFormat("nl-NL", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Amsterdam" }).format(new Date(item.started_at))}</p></div><button className="rounded border border-slate-700 px-3 py-2 text-sm text-slate-100" type="button" onClick={() => editActivity(item)}>Bewerken</button></div></article>)}{!activities.length && <div className="rounded border border-dashed border-slate-700 p-4 text-slate-300"><p>Nog geen activiteiten.</p><button className="mt-3 rounded bg-cyan-300 px-3 py-2 text-sm font-medium text-slate-950" type="button" onClick={() => editActivity()}>Activiteit toevoegen</button></div>}</div></div></section>
    <section className="mt-8 grid gap-4 lg:grid-cols-2"><form className="rounded-2xl border border-slate-800 bg-slate-900 p-5" onSubmit={saveWeight}><h2 className="text-xl font-semibold text-white">{weightEdit ? "Gewicht corrigeren" : "Gewicht toevoegen"}</h2><div className="mt-4 grid gap-4"><label className="grid gap-1 text-sm text-slate-200">Moment<input className="rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white" type="datetime-local" required value={weight.measured_at} onChange={(event) => setWeight({ ...weight, measured_at: event.target.value })} /></label><label className="grid gap-1 text-sm text-slate-200">Gewicht<input className="rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white" type="number" min="0.01" step="0.01" required value={weight.value} onChange={(event) => setWeight({ ...weight, value: event.target.value })} /></label><label className="grid gap-1 text-sm text-slate-200">Eenheid<select className="rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white" value={weight.unit} onChange={(event) => setWeight({ ...weight, unit: event.target.value as WeightValues["unit"] })}><option value="kg">kg</option><option value="lb">lb</option></select></label><label className="grid gap-1 text-sm text-slate-200">Bron<input className="rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white" required value={weight.source} onChange={(event) => setWeight({ ...weight, source: event.target.value })} /></label><button className="w-fit rounded bg-cyan-300 px-4 py-2 font-medium text-slate-950 disabled:opacity-60" disabled={saving} type="submit">{saving ? "Bezig…" : "Bewaar gewicht"}</button></div></form>
      <form className="rounded-2xl border border-slate-800 bg-slate-900 p-5" onSubmit={saveActivity}><h2 className="text-xl font-semibold text-white">{activityEdit ? "Activiteit corrigeren" : "Activiteit toevoegen"}</h2><div className="mt-4 grid gap-4"><label className="grid gap-1 text-sm text-slate-200">Type activiteit<input className="rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white" required value={activity.activity_type} onChange={(event) => setActivity({ ...activity, activity_type: event.target.value })} /></label><label className="grid gap-1 text-sm text-slate-200">Start<input className="rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white" type="datetime-local" required value={activity.started_at} onChange={(event) => setActivity({ ...activity, started_at: event.target.value })} /></label><label className="grid gap-1 text-sm text-slate-200">Einde<input className="rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white" type="datetime-local" required value={activity.ended_at} onChange={(event) => setActivity({ ...activity, ended_at: event.target.value })} /></label><label className="grid gap-1 text-sm text-slate-200">Bron<input className="rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white" required value={activity.source} onChange={(event) => setActivity({ ...activity, source: event.target.value })} /></label><button className="w-fit rounded bg-cyan-300 px-4 py-2 font-medium text-slate-950 disabled:opacity-60" disabled={saving} type="submit">{saving ? "Bezig…" : "Bewaar activiteit"}</button></div></form></section>
    {error && <p className="mt-4 text-sm text-red-300" role="alert">{error}</p>}
  </main>;
}
