"use client";

import { FormEvent, useEffect, useState, type ReactNode } from "react";

import { StitchPanel, StitchUnavailable } from "./stitch-primitives";

type Kind = "text" | "snippet" | "quick_task" | "voice_reference";
type Status = "captured" | "triaged" | "archived" | "deleted";
type Entry = { id: string; kind: Kind; status: Status; title: string; summary: string | null; created_at: string; updated_at: string; archived: boolean; deleted: boolean };
type EntriesResponse = { entries: Entry[]; page: number; limit: number; has_more: boolean };

const kindLabel: Record<Kind, string> = { text: "Tekst", snippet: "Snippet", quick_task: "Snelle taak", voice_reference: "Spraakreferentie" };
const statusLabel: Record<Status, string> = { captured: "Inbox", triaged: "Getrieerd", archived: "Archief", deleted: "Verwijderd" };

export interface IdeasClientProps {}

export function IdeasClient(_: IdeasClientProps) {
  const [entries, setEntries] = useState<Entry[]>([]);
  const [kind, setKind] = useState<Kind | "">("");
  const [status, setStatus] = useState<Status | "">("");
  const [view, setView] = useState<"inbox" | "archive" | "all">("inbox");
  const [capture, setCapture] = useState("");
  const [captureKind, setCaptureKind] = useState<Kind>("text");
  const [pairingCode, setPairingCode] = useState("");
  const [voiceReference, setVoiceReference] = useState("");
  const [state, setState] = useState<"loading" | "ready" | "pairing" | "error">("loading");
  const [notice, setNotice] = useState<string | null>(null);

  async function load() { setState("loading"); const params = new URLSearchParams({ view, limit: "25" }); if (kind) params.set("kind", kind); if (status) params.set("status", status); try { const response = await fetch(`/api/browser/stream-entries?${params}`, { cache: "no-store" }); if (response.status === 401) { setState("pairing"); return; } if (!response.ok) throw new Error("unavailable"); const body: EntriesResponse = await response.json(); setEntries(body.entries); setState("ready"); } catch { setState("error"); } }
  useEffect(() => { void load(); }, [kind, status, view]);
  async function pair(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setNotice(null); const response = await fetch("/api/browser-sessions/pair", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pairing_code: pairingCode }) }); setPairingCode(""); if (!response.ok) { setNotice("Koppelen mislukt of code is verlopen."); return; } await load(); }
  async function mutate(path: string, method: "POST" | "DELETE", body?: unknown) { setNotice(null); const response = await fetch(path, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); if (response.status === 401) { setState("pairing"); return; } if (!response.ok) { setNotice("Actie niet beschikbaar voor dit item."); return; } await load(); }
  async function submitCapture(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (captureKind === "voice_reference") { if (!voiceReference.trim()) return; await mutate("/api/stream-entries", "POST", { kind: captureKind, voice_reference: { source: "browser", reference_id: voiceReference } }); setVoiceReference(""); return; } if (!capture.trim()) return; await mutate("/api/stream-entries", "POST", { kind: captureKind, content: capture }); setCapture(""); }
  async function logout() { await fetch("/api/browser-sessions/current", { method: "DELETE" }); setEntries([]); setState("pairing"); }

  return <main className="mx-auto max-w-[1600px] px-margin-mobile py-space-lg md:px-margin-desktop" aria-label="Idea Incubator">
    {state === "ready" && <><section className="cortex-stitch-panel p-4" aria-label="Capture dock"><form onSubmit={submitCapture}><div className="flex items-center gap-3"><span className="material-symbols-outlined text-primary" aria-hidden="true">psychology</span>{captureKind === "voice_reference" ? <input className="m-0 flex-1 border-0 bg-transparent p-0 font-headline text-headline-sm text-on-surface placeholder:text-outline focus:ring-0" id="capture" maxLength={500} placeholder="Bestaande spraakreferentie-id" value={voiceReference} onChange={(event) => setVoiceReference(event.target.value)} /> : <input className="m-0 flex-1 border-0 bg-transparent p-0 font-headline text-headline-sm text-on-surface placeholder:text-outline focus:ring-0" id="capture" maxLength={4000} placeholder="Paste unstructured thought, paste raw markdown, dictate voice capture, or dump URL…" value={capture} onChange={(event) => setCapture(event.target.value)} />}</div><div className="mt-4 flex flex-wrap items-center gap-2 border-t border-surface-container-highest pt-3"><label className="sr-only" htmlFor="capture-kind">Capture type</label><select className="m-0 w-auto border-0 bg-surface-container-low px-2 py-1 font-mono text-mono-data-sm text-on-surface" id="capture-kind" value={captureKind} onChange={(event) => setCaptureKind(event.target.value as Kind)}>{(["text", "snippet", "quick_task", "voice_reference"] as const).map((item) => <option key={item} value={item}>{kindLabel[item]}</option>)}</select><span className="rounded bg-surface-container-low px-2 py-1 font-mono text-mono-data-sm text-outline">Paired browser source</span><button className="ml-auto rounded bg-primary px-4 py-2 font-headline text-headline-sm text-on-primary" type="submit">Ingest</button></div></form></section>
      <section className="mt-3 flex flex-wrap items-center justify-between gap-3" aria-label="Idea filters"><div className="flex flex-wrap gap-2"><FilterButton active={view === "all"} onClick={() => setView("all")}>All ingested {entries.length}</FilterButton><FilterButton active={view === "inbox"} onClick={() => setView("inbox")}>Unprocessed</FilterButton><FilterButton active={status === "triaged"} onClick={() => setStatus(status === "triaged" ? "" : "triaged")}>Auto-structured</FilterButton><FilterButton active={view === "archive"} onClick={() => setView("archive")}>Archived</FilterButton></div><div className="flex gap-2"><select className="m-0 w-auto border-0 bg-surface-container-low px-2 py-1 font-mono text-mono-data-sm text-on-surface" value={kind} onChange={(event) => setKind(event.target.value as Kind | "")}><option value="">Alle typen</option>{(Object.keys(kindLabel) as Kind[]).map((item) => <option key={item} value={item}>{kindLabel[item]}</option>)}</select><select className="m-0 w-auto border-0 bg-surface-container-low px-2 py-1 font-mono text-mono-data-sm text-on-surface" value={status} onChange={(event) => setStatus(event.target.value as Status | "")}><option value="">Alle statussen</option>{(Object.keys(statusLabel) as Status[]).map((item) => <option key={item} value={item}>{statusLabel[item]}</option>)}</select></div></section>
      {notice && <p className="mt-3 text-body-sm text-error">{notice}</p>}
      <section className="mt-4 grid gap-3 xl:grid-cols-12" aria-label="Second Brain workspace"><div className="space-y-3 xl:col-span-4"><PanelLabel title="Raw Ingestion Stream" detail="LIVE INFLOW" />{entries.map((entry) => <EntryCard entry={entry} key={entry.id} onArchive={() => void mutate(`/api/stream-entries/${entry.id}/archive`, "POST")} onDelete={() => void mutate(`/api/stream-entries/${entry.id}`, "DELETE")} onTriage={() => void mutate(`/api/stream-entries/${entry.id}/triage`, "POST", {})} />)}{!entries.length && <StitchPanel className="p-3"><p className="text-body-sm text-on-surface-variant">Geen entries voor deze filters.</p></StitchPanel>}</div><div className="space-y-3 xl:col-span-5"><PanelLabel title="Processing matrix" detail="UNAVAILABLE BY SOURCE" /><StitchUnavailable title="Selected entry synthesis" detail="Geen bron voor AI-structurering, transcriptie, verrijking of automatische classificatie. Gebruik de feitelijke inbox-, triage- en archiefflow." /><StitchUnavailable title="Action sub-tasks" detail="Er is geen bron voor gegenereerde subtaken." /></div><aside className="space-y-3 xl:col-span-3"><PanelLabel title="Semantic intelligence" detail="UNAVAILABLE BY SOURCE" /><StitchUnavailable title="Pattern detection" detail="Geen RAG-, embeddings- of vectorzoekbron." /><StitchUnavailable title="Topic clusters" detail="Geen geverifieerde clusterbron." /><StitchUnavailable title="Resurfacing queue" detail="Geen bron voor resurfacing of snooze." /></aside></section><div className="mt-4 flex justify-end"><button className="font-mono text-mono-data-sm text-outline hover:text-on-surface" onClick={() => void logout()} type="button">Uitloggen browser-session</button></div></>}
    {state === "pairing" && <section className="mx-auto mt-12 max-w-xl"><StitchPanel className="p-5"><p className="font-label-caps text-label-caps text-primary">SECOND BRAIN AUTH</p><h1 className="mt-2 font-headline text-headline-lg text-on-surface">Gebruiker koppelen</h1><p className="mt-2 text-body-sm text-on-surface-variant">Gebruik een eenmalige gebruikerscode. Meerdere browsers en apparaten delen daarna dezelfde gebruikersinbox.</p><form className="mt-5 flex gap-3" onSubmit={pair}><label className="sr-only" htmlFor="pairing-code">Gebruikerscode</label><input id="pairing-code" required value={pairingCode} onChange={(event) => setPairingCode(event.target.value)} /><button className="rounded bg-primary px-4 py-2 font-headline text-headline-sm text-on-primary" type="submit">Koppelen</button></form>{notice && <p className="mt-3 text-body-sm text-error">{notice}</p>}</StitchPanel></section>}
    {state === "error" && <section className="mx-auto mt-12 max-w-xl"><StitchUnavailable title="Second Brain unavailable" detail="De stream-entry bron is nu niet beschikbaar." /><button className="mt-3 font-mono text-mono-data-sm text-primary" onClick={() => void load()} type="button">Opnieuw proberen</button></section>}
    {state === "loading" && <section className="mx-auto mt-12 max-w-xl"><StitchPanel className="p-5"><p className="font-mono text-mono-data-sm text-outline">SECOND BRAIN LOADING…</p></StitchPanel></section>}
  </main>;
}

interface FilterButtonProps { readonly active: boolean; readonly children: ReactNode; readonly onClick: () => void; }
function FilterButton({ active, children, onClick }: FilterButtonProps) { return <button className={`rounded px-2 py-1 font-mono text-mono-data-sm ${active ? "bg-primary/15 text-primary" : "bg-surface-container-low text-outline"}`} onClick={onClick} type="button">{children}</button>; }
interface PanelLabelProps { readonly title: string; readonly detail: string; }
function PanelLabel({ title, detail }: PanelLabelProps) { return <div className="flex items-center justify-between gap-2"><h2 className="font-label-caps text-label-caps text-outline">{title}</h2><span className="rounded bg-surface-container-high px-2 py-1 font-mono text-mono-data-sm text-outline">{detail}</span></div>; }
interface EntryCardProps { readonly entry: Entry; readonly onTriage: () => void; readonly onArchive: () => void; readonly onDelete: () => void; }
function EntryCard({ entry, onTriage, onArchive, onDelete }: EntryCardProps) { return <StitchPanel className="p-3"><div className="flex items-start justify-between gap-2"><div><p className="font-mono text-mono-data-sm text-primary">{kindLabel[entry.kind]} · {statusLabel[entry.status]}</p><h3 className="mt-2 font-headline text-headline-md text-on-surface">{entry.title}</h3>{entry.summary && entry.summary !== entry.title && <p className="mt-2 line-clamp-3 text-body-sm text-on-surface-variant">{entry.summary}</p>}<p className="mt-3 font-mono text-mono-data-sm text-outline">{formatTime(entry.created_at)}</p></div><div className="flex flex-col gap-1 text-right">{entry.status === "captured" && <button className="font-mono text-mono-data-sm text-primary" onClick={onTriage} type="button">Triage</button>}{!entry.archived && !entry.deleted && <button className="font-mono text-mono-data-sm text-on-surface-variant" onClick={onArchive} type="button">Archiveer</button>}{!entry.deleted && <button className="font-mono text-mono-data-sm text-error" onClick={onDelete} type="button">Verwijder</button>}</div></div></StitchPanel>; }
function formatTime(value: string) { return new Intl.DateTimeFormat("nl-NL", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Amsterdam" }).format(new Date(value)); }
