"use client";

import { FormEvent, useEffect, useState } from "react";

type Frequency = "daily" | "weekly" | "selected_weekdays";
type Routine = { id: string; title: string; active: boolean; frequency: Frequency; weekdays: number[]; reminder_time: string; };
type Values = { title: string; active: boolean; frequency: Frequency; weekdays: number[]; reminder_time: string; };
const days = ["maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag", "zondag"];
const empty: Values = { title: "", active: true, frequency: "daily", weekdays: [], reminder_time: "09:00" };

function formValues(routine?: Routine): Values { return routine ? { title: routine.title, active: routine.active, frequency: routine.frequency, weekdays: routine.weekdays ?? [], reminder_time: routine.reminder_time.slice(0, 5) } : empty; }
function errorMessage(body: unknown) { if (typeof body === "object" && body && "detail" in body) { const detail = (body as { detail: unknown }).detail; return typeof detail === "string" ? detail : Array.isArray(detail) ? detail.map((item) => typeof item === "object" && item && "msg" in item ? String(item.msg) : String(item)).join(" ") : "Routine kon niet worden bewaard."; } return "Routine kon niet worden bewaard."; }
function productDate() { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Amsterdam", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(); const part = (type: string) => parts.find((item) => item.type === type)?.value; return `${part("year")}-${part("month")}-${part("day")}`; }
function schedule(routine: Routine) { if (routine.frequency === "daily") return "Dagelijks"; const selected = (routine.weekdays ?? []).map((day) => days[day - 1]).join(", "); return routine.frequency === "weekly" ? `Wekelijks: ${selected}` : `Gekozen dagen: ${selected}`; }

export function RoutinePage({ initialRoutines, loadError }: { initialRoutines: Routine[]; loadError?: string | null }) {
  const [routines, setRoutines] = useState(initialRoutines);
  const [editing, setEditing] = useState<Routine | null>(null);
  const [values, setValues] = useState<Values>(empty);
  const [occurrenceDate, setOccurrenceDate] = useState(productDate);
  const [completed, setCompleted] = useState<Record<string, Set<string>>>({});
  const [error, setError] = useState(""); const [loading, setLoading] = useState(false);

  useEffect(() => { Promise.all(initialRoutines.map(async (routine) => { const response = await fetch(`/api/routines/${routine.id}/completions`); return [routine.id, response.ok ? await response.json() as Array<{ occurrence_date: string }> : []] as const; })).then((entries) => setCompleted(Object.fromEntries(entries.map(([id, history]) => [id, new Set(history.map((item) => item.occurrence_date))])))); }, [initialRoutines]);
  function start(routine?: Routine) { setEditing(routine ?? null); setValues(formValues(routine)); setError(""); }
  function setDay(day: number, selected: boolean) { setValues((current) => ({ ...current, weekdays: selected ? [...current.weekdays, day].sort() : current.weekdays.filter((value) => value !== day) })); }

  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const response = await fetch(editing ? `/api/routines/${editing.id}` : "/api/routines", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, weekdays: values.frequency === "daily" ? [] : values.weekdays }) }); if (!response.ok) { setError(errorMessage(await response.json().catch(() => null))); setLoading(false); return; } const saved: Routine = await response.json(); setRoutines((current) => editing ? current.map((routine) => routine.id === saved.id ? saved : routine) : [...current, saved]); start(); setLoading(false); }
  async function completion(routine: Routine) { const done = completed[routine.id]?.has(occurrenceDate); setLoading(true); setError(""); const response = await fetch(`/api/routines/${routine.id}/${done ? "uncomplete" : "complete"}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ occurrence_date: occurrenceDate }) }); if (!response.ok) { setError(errorMessage(await response.json().catch(() => null))); setLoading(false); return; } setCompleted((current) => { const next = new Set(current[routine.id] ?? []); done ? next.delete(occurrenceDate) : next.add(occurrenceDate); return { ...current, [routine.id]: next }; }); setLoading(false); }

  return <main className="mx-auto min-h-screen max-w-5xl px-5 py-6 sm:px-8 sm:py-10"><a className="text-cyan-300 underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300" href="/">← Terug naar Vandaag</a><header className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold text-white sm:text-4xl">Routines</h1><p className="mt-1 text-slate-400">Planning en voltooiing volgen bestaande routine-semantiek.</p></div><button className="rounded bg-cyan-300 px-4 py-2 font-medium text-slate-950" type="button" onClick={() => start()}>Nieuwe routine</button></header>
    <label className="mt-6 grid max-w-xs gap-1 text-sm text-slate-200">Datum voor voltooiing<input className="rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white" type="date" value={occurrenceDate} onChange={(event) => setOccurrenceDate(event.target.value)} /></label>
    {loadError && <p className="mt-5 text-sm text-red-300" role="alert">{loadError}</p>}
    <section className="mt-5 grid gap-4" aria-label="Routinelijst">{routines.map((routine) => { const done = completed[routine.id]?.has(occurrenceDate); return <article className="rounded-2xl border border-slate-800 bg-slate-900 p-5" key={routine.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-cyan-300">{routine.active ? "Actief" : "Inactief"} · {routine.reminder_time.slice(0, 5)}</p><h2 className="mt-1 text-xl font-semibold text-white">{routine.title}</h2><p className="mt-2 text-sm text-slate-300">{schedule(routine)}</p><p className="mt-1 text-sm text-slate-400">{done ? `Voltooid op ${occurrenceDate}` : `Nog niet voltooid op ${occurrenceDate}`}</p></div><div className="flex flex-wrap gap-2"><button className="rounded border border-slate-700 px-3 py-2 text-sm text-slate-100" type="button" onClick={() => start(routine)}>Bekijken / bewerken</button><button className="rounded bg-cyan-300 px-3 py-2 text-sm font-medium text-slate-950" disabled={loading} type="button" onClick={() => completion(routine)}>{done ? "Opnieuw openen" : "Voltooien"}</button></div></div></article>; })}{!routines.length && <div className="rounded-2xl border border-dashed border-slate-700 p-6 text-slate-300"><p>Nog geen routines.</p><button className="mt-3 rounded bg-cyan-300 px-4 py-2 font-medium text-slate-950" type="button" onClick={() => start()}>Nieuwe routine</button></div>}</section>
    <section className="mt-8 rounded-2xl border border-slate-800 bg-slate-900 p-5" aria-labelledby="routine-form-title"><h2 id="routine-form-title" className="text-xl font-semibold text-white">{editing ? "Routine bewerken" : "Nieuwe routine"}</h2><form className="mt-4 grid gap-4 sm:grid-cols-2" onSubmit={submit}><label className="grid gap-1 text-sm text-slate-200 sm:col-span-2">Titel<input className="rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white" required value={values.title} onChange={(event) => setValues({ ...values, title: event.target.value })} /></label><label className="grid gap-1 text-sm text-slate-200">Planning<select className="rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white" value={values.frequency} onChange={(event) => setValues({ ...values, frequency: event.target.value as Frequency })}><option value="daily">Dagelijks</option><option value="weekly">Wekelijks</option><option value="selected_weekdays">Gekozen weekdagen</option></select></label><label className="grid gap-1 text-sm text-slate-200">Herinnering<input className="rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white" type="time" required value={values.reminder_time} onChange={(event) => setValues({ ...values, reminder_time: event.target.value })} /></label><fieldset className="sm:col-span-2"><legend className="text-sm text-slate-200">Weekdagen{values.frequency === "daily" ? " (niet gebruikt voor dagelijks)" : ""}</legend><div className="mt-2 flex flex-wrap gap-3">{days.map((day, index) => <label className="flex items-center gap-1 text-sm text-slate-300" key={day}><input checked={values.weekdays.includes(index + 1)} disabled={values.frequency === "daily"} type="checkbox" onChange={(event) => setDay(index + 1, event.target.checked)} />{day}</label>)}</div></fieldset><label className="flex items-center gap-2 text-sm text-slate-200 sm:col-span-2"><input checked={values.active} type="checkbox" onChange={(event) => setValues({ ...values, active: event.target.checked })} />Actief</label>{error && <p className="sm:col-span-2 text-sm text-red-300" role="alert">{error}</p>}<div className="flex flex-wrap gap-3 sm:col-span-2"><button className="rounded bg-cyan-300 px-4 py-2 font-medium text-slate-950 disabled:opacity-60" disabled={loading} type="submit">{loading ? "Bezig…" : editing ? "Bewaar wijzigingen" : "Maak routine"}</button>{editing && <button className="rounded border border-slate-700 px-4 py-2 text-slate-100" type="button" onClick={() => start()}>Annuleer</button>}</div></form></section>
  </main>;
}
